DEV-3324 Add client proxy to allow reconnects
hartwigmedical/platinum pull request #42
Opened 2023-06-12 15:37 UTC by nedleitch

Add the KubernetesClientProxy class so that the several new places from which there may now be Kubernetes client exceptions thrown can request a client re-authorise rather than failing that sample's run or throwing the exception all the way back up.

Also start breaking up the massive `kubernetes` pakcage which did not really have just Kubernetes-related stuff in it.

Lastly override the default threading as the application was taking longer than acceptable to run in Kubernetes. This will have to be improved in a more robust way; this is a temporary improvement to get the 5.32 rerun done.

2023-06-12 15:44 UTC, pauldwolfe requested changes

2023-06-12 15:44 UTC, pauldwolfe commented on src/main/java/com/hartwig/platinum/kubernetes/KubernetesClientProxy.java
> +    private Provider<KubernetesClient> kubernetesClientProvider;
why a lazy init provider? Could it not just wrap the client? If not I guess can be final?

2023-06-12 15:47 UTC, nedleitch commented on src/main/java/com/hartwig/platinum/kubernetes/KubernetesClientProxy.java
> +        if (!processRunner.execute(of("kubectl", "get", "configmaps"))) {
Yeah that's better, thanks.

2023-06-12 16:26 UTC, pauldwolfe commented on platinum
> +    java -Djava.util.concurrent.ForkJoinPool.common.parallelism=8 -jar $JAR "$@"
Sorry should read the description :)

2023-06-13 14:04 UTC, pauldwolfe approved these changes

2023-06-13 14:35 UTC, merged